package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func migrate(t *testing.T, src string) (string, Result) {
	t.Helper()
	out, res, err := Migrate("x.go", []byte(src))
	if err != nil {
		t.Fatalf("Migrate: %v", err)
	}
	return string(out), res
}

func mustContain(t *testing.T, out string, want ...string) {
	t.Helper()
	for _, w := range want {
		if !strings.Contains(out, w) {
			t.Errorf("manca %q in:\n%s", w, out)
		}
	}
}

func TestMigrate_QualificatoriEImport(t *testing.T) {
	out, res := migrate(t, `package a

import (
	"fmt"

	core "github.com/GPA-Gruppo-Progetti-Avanzati-SRL/go-core-app"
)

func F(p core.Properties) *core.ApplicationError {
	fmt.Println(core.GetHostname())
	core.Provide(nil)
	return core.TechnicalError()
}
`)
	if !res.Changed {
		t.Fatal("file non modificato")
	}
	mustContain(t, out,
		`"github.com/GPA-Gruppo-Progetti-Avanzati-SRL/go-core-app/properties"`,
		`"github.com/GPA-Gruppo-Progetti-Avanzati-SRL/go-core-app/utils"`,
		"p properties.Properties", "*core.Error", "utils.GetHostname()", "core.Provide(nil)")
}

// Stringhe, commenti e campi omonimi restano com'erano: la versione in shell li riscriveva.
func TestMigrate_NonToccaStringheCommentiCampi(t *testing.T) {
	out, _ := migrate(t, `package a

import "github.com/GPA-Gruppo-Progetti-Avanzati-SRL/go-core-app"

type holder struct{ core struct{ Task string } }

// vedi core.Task nella doc
func F(s holder) (string, string, core.Properties) {
	return "core.Task", s.core.Task, nil
}
`)
	mustContain(t, out, "// vedi core.Task nella doc", `"core.Task"`, "s.core.Task", "properties.Properties")
	if strings.Contains(out, `go-core-app"`+"\n") && !strings.Contains(out, "core.") {
		t.Fatal("import della radice lasciato senza usi")
	}
}

func TestMigrate_ImportConCommentoEAlias(t *testing.T) {
	out, res := migrate(t, `package a

import (
	coreapp "github.com/GPA-Gruppo-Progetti-Avanzati-SRL/go-core-app" // runtime
)

var _ = coreapp.ConcurrentN[int, int]
`)
	if !res.Changed {
		t.Fatal("un import con un commento in coda non deve far saltare il file")
	}
	mustContain(t, out, "utils.ConcurrentN[int, int]")
	if strings.Contains(out, `go-core-app" `) || strings.Contains(out, "coreapp.") {
		t.Fatalf("import della radice non rimosso pur senza usi:\n%s", out)
	}
}

// Un nome locale uguale al package nuovo: l'import prende un alias invece di rompere il codice.
func TestMigrate_CollisioneConNomeLocale(t *testing.T) {
	out, _ := migrate(t, `package a

import "github.com/GPA-Gruppo-Progetti-Avanzati-SRL/go-core-app"

func F(utils int) string { return core.GetHostname() }
`)
	mustContain(t, out, `coreutils "github.com/GPA-Gruppo-Progetti-Avanzati-SRL/go-core-app/utils"`, "coreutils.GetHostname()", "func F(utils int)")
}

func TestMigrate_GeneratiEDotImport(t *testing.T) {
	gen := "// Code generated by mockgen. DO NOT EDIT.\n\npackage a\n\nimport \"github.com/GPA-Gruppo-Progetti-Avanzati-SRL/go-core-app\"\n\nvar _ core.Properties\n"
	if out, res := migrate(t, gen); res.Changed || out != gen {
		t.Fatal("un file generato non va toccato")
	}
	_, res := migrate(t, "package a\n\nimport . \"github.com/GPA-Gruppo-Progetti-Avanzati-SRL/go-core-app\"\n\nvar _ Properties\n")
	if res.Skipped == "" {
		t.Fatal("un dot-import va segnalato, non saltato in silenzio")
	}
}

func TestMigrate_SoloRinomino(t *testing.T) {
	src := "package a\n\nimport (\n\t\"fmt\"\n\n\tcore \"github.com/GPA-Gruppo-Progetti-Avanzati-SRL/go-core-app\"\n)\n\nvar _ *core.ApplicationError\nvar _ = fmt.Sprint\n"
	out, _ := migrate(t, src)
	want := strings.Replace(src, "core.ApplicationError", "core.Error", 1)
	if out != want {
		t.Fatalf("atteso solo il rinomino, import invariati:\n%s", out)
	}
}

func TestMigrate_Idempotente(t *testing.T) {
	src := "package a\n\nimport core \"github.com/GPA-Gruppo-Progetti-Avanzati-SRL/go-core-app\"\n\nvar _ core.Properties\nvar _ *core.ApplicationError\n"
	once, _ := migrate(t, src)
	twice, res := migrate(t, once)
	if res.Changed || twice != once {
		t.Fatalf("seconda esecuzione non neutra:\n%s", twice)
	}
}

// TestTabella_SimboliEsistono: ogni simbolo della tabella esiste davvero nel package di
// destinazione, e i rinomini esistono nella radice. È ciò che avrebbe segnalato i
// DefaultMetrics* dimenticati dalla versione in shell nel verso opposto: qui una voce che non
// corrisponde più al codice fa fallire il test.
func TestTabella_SimboliEsistono(t *testing.T) {
	exported := func(dir string) map[string]bool {
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Fatal(err)
		}
		fset := token.NewFileSet()
		names := map[string]bool{}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
				continue
			}
			f, err := parser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, 0)
			if err != nil {
				t.Fatal(err)
			}
			for name := range f.Scope.Objects {
				if ast.IsExported(name) {
					names[name] = true
				}
			}
		}
		return names
	}
	for pkg, syms := range Moved {
		have := exported(filepath.Join("..", "..", pkg))
		for _, s := range syms {
			if !have[s] {
				t.Errorf("%s.%s: non esiste in %s", pkg, s, pkg)
			}
		}
	}
	root := exported(filepath.Join("..", ".."))
	for old, name := range Renamed {
		if !root[name] {
			t.Errorf("core.%s (ex %s) non esiste nella radice", name, old)
		}
		if root[old] {
			t.Errorf("core.%s esiste ancora: il rinomino non serve più", old)
		}
	}
	for s := range symbolPkg {
		if root[s] {
			t.Errorf("core.%s esiste ancora nella radice: la voce sposterebbe un simbolo che non si è mosso", s)
		}
	}
}
